name: Deploy 🚀

on:
    push:
        branches: [main]
permissions:
    contents: write
jobs:
    build:
        timeout-minutes: 15
        continue-on-error: true
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet: ["7.0.x"]

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ matrix.dotnet }}
            - name: Install dependencies
              run: dotnet restore src
            - name: Build
              run: dotnet build src -c Release --no-restore --nologo

    deploy:
        needs: build
        timeout-minutes: 15
        continue-on-error: true
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "7.0.x"
            # Install dotnet wasm buildtools workload
            - name: Install .NET WASM Build Tools
              run: dotnet workload install wasm-tools
            - name: Install dependencies
              run: dotnet restore src
            - name: Publish with dotnet
              run: dotnet publish src/CaseyUniverse.DOC -c Release --output build --no-restore --nologo
            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: build/wwwroot # The folder the action should deploy.
                  SINGLE_COMMIT: true
