name: .NET

on:
  push:
    branches: [main]

jobs:
  build:
    timeout-minutes: 15
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet: ["7.0.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Install dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src -c Release --no-restore

  deploy:
    needs: build
    timeout-minutes: 15
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore src
      - name: Publish with dotnet
        run: dotnet publish src/FurryBlue.DOC -c Release --output build --no-restore
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/wwwroot # The folder the action should deploy.
          SINGLE_COMMIT: true
